domain_name: 'caasp.is'

repos:
  - { name: 'prod', url: 'http://download.suse.de/ibs/SUSE/Products/SLE-Product-SLES/15-SP2/x86_64/product' }
  - { name: 'prod_up', url: 'http://download.suse.de/ibs/SUSE/Updates/SLE-Product-SLES/15-SP2/x86_64/update' }

  - { name: 'base_sys', url: 'http://download.suse.de/ibs/SUSE/Products/SLE-Module-Basesystem/15-SP2/x86_64/product' }
  - { name: 'base_sys_up', url: 'http://download.suse.de/ibs/SUSE/Updates/SLE-Module-Basesystem/15-SP2/x86_64/update' }

  - { name: 'srv_app', url: 'http://download.suse.de/ibs/SUSE/Products/SLE-Module-Server-Applications/15-SP2/x86_64/product' }
  - { name: 'srv_app_up', url: 'http://download.suse.de/ibs/SUSE/Updates/SLE-Module-Server-Applications/15-SP2/x86_64/update' }

  - { name: 'contain', url: 'http://download.suse.de/ibs/SUSE/Products/SLE-Module-Containers/15-SP2/x86_64/product' }
  - { name: 'contain_up', url: 'http://download.suse.de/ibs/SUSE/Updates/SLE-Module-Containers/15-SP2/x86_64/update' }

  - { name: 'caasp', url: 'http://download.suse.de/ibs/SUSE/Products/SUSE-CAASP/5/x86_64/product' }
  - { name: 'caasp_up', url: 'http://download.suse.de/ibs/SUSE/Updates/SUSE-CAASP/5/x86_64/update' }
